import { CommonModule } from '@angular/common';
import { Component, OnInit } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { RouterLink } from '@angular/router';
import { RewardsService } from './services/rewards.service';
import { ToastService } from './toast.service';

@Component({
  selector: 'app-admin-rewards', standalone: true, imports: [CommonModule, FormsModule, RouterLink],
  template: `
    <main class="admin-rewards">
      <header><div><p>CARSHARE247 / REWARDS</p><h1>Rewards operations</h1></div><div><a routerLink="/Kumaresh/dashboard">Back to dashboard</a><button (click)="exportCsv()">Export CSV</button></div></header>
      <section class="metrics"><div><span>Total referrals</span><strong>{{metrics.totalReferrals||0}}</strong></div><div><span>Rewarded</span><strong>{{metrics.rewardedReferrals||0}}</strong></div><div><span>Coins issued</span><strong>{{metrics.coinsIssued||0}}</strong></div><div><span>Coins redeemed</span><strong>{{metrics.coinsRedeemed||0}}</strong></div><div><span>Subscription coins</span><strong>{{metrics.coinsUsedForSubscription||0}}</strong></div><div><span>Pending payouts</span><strong>{{metrics.pendingRedemptions||0}}</strong></div></section>
      <nav><button [class.active]="tab==='redemptions'" (click)="tab='redemptions'">Redemptions</button><button [class.active]="tab==='referrals'" (click)="tab='referrals'">Referrals</button><button [class.active]="tab==='settings'" (click)="tab='settings'">Settings & adjustments</button></nav>
      <section *ngIf="tab==='redemptions'">
        <div class="toolbar"><h2>Redemption requests</h2><input [(ngModel)]="query" placeholder="Search user, mobile, status"><select [(ngModel)]="status"><option value="">All statuses</option><option *ngFor="let value of statuses">{{value}}</option></select></div>
        <div class="table"><table><thead><tr><th>User</th><th>Bank</th><th>Amount</th><th>Requested</th><th>Status</th><th>Actions</th></tr></thead><tbody><tr *ngFor="let item of filteredRedemptions"><td><strong>{{item.userName}}</strong><small>{{item.userType}} · {{item.mobileNumber}}</small></td><td>{{item.bankName}}<small>{{item.accountHolderName}} · {{item.accountNumber}} · {{item.ifsc}}</small></td><td>{{item.requestedAmount}} coins</td><td>{{item.requestDate|date:'medium'}}</td><td><span class="status">{{item.status}}</span></td><td class="actions"><button *ngIf="item.status==='PENDING'" (click)="transition(item,'PROCESSING')">Process</button><button *ngIf="item.status==='PROCESSING'" (click)="markPaid(item)">Mark paid</button><button *ngIf="item.status==='PAID'" (click)="transition(item,'CLOSED')">Close</button><button class="danger" *ngIf="item.status==='PENDING'||item.status==='PROCESSING'" (click)="reject(item)">Reject</button></td></tr></tbody></table></div>
      </section>
      <section *ngIf="tab==='referrals'"><div class="toolbar"><h2>Referral audit</h2><input [(ngModel)]="query" placeholder="Search referrals"></div><div class="table"><table><thead><tr><th>Referrer</th><th>Referred user</th><th>Registration</th><th>Coins</th><th>Status</th></tr></thead><tbody><tr *ngFor="let item of filteredReferrals"><td>{{item.referrer}}</td><td>{{item.referredUser}}</td><td>{{item.registrationDate|date:'medium'}}</td><td>{{item.coinsAwarded}}</td><td><span class="status">{{item.status}}</span></td></tr></tbody></table></div></section>
      <section *ngIf="tab==='settings'" class="settings"><h2>Program settings</h2><label><input type="checkbox" [(ngModel)]="settings.referralEnabled"> Referral program enabled</label><label>Coins per referral<input type="number" min="0" [(ngModel)]="settings.coinsPerReferral"></label><label>Minimum redemption<input type="number" min="1" [(ngModel)]="settings.minimumRedemption"></label><label>Maximum redemption<input type="number" min="1" [(ngModel)]="settings.maximumRedemption"></label><label>Subscription coin limit (%)<input type="number" min="0" max="99" [(ngModel)]="settings.subscriptionCoinPercentage"></label><label>Referral registration URL<input [(ngModel)]="settings.referralBaseUrl"></label><button class="primary" (click)="saveSettings()">Save settings</button><hr><h2>Wallet adjustment</h2><label>User ID<input [(ngModel)]="adjustment.userId"></label><label>Coins (negative to deduct)<input type="number" [(ngModel)]="adjustment.amount"></label><label>Reason<input [(ngModel)]="adjustment.reason"></label><button (click)="adjust()">Apply adjustment</button></section>
    </main>
  `,
  styles:[`
    :host{display:block}.admin-rewards{padding:24px 0 48px;color:#172033}header{display:flex;justify-content:space-between;align-items:center;gap:16px}header p{font-size:.75rem;font-weight:800;color:#087b6c;margin:0}header h1{margin:4px 0}header div:last-child{display:flex;gap:8px}a,button{border:1px solid #cad5dc;background:#fff;color:#172033;border-radius:6px;padding:9px 12px;text-decoration:none;font-weight:700;cursor:pointer}.primary,.active{background:#087b6c;color:#fff;border-color:#087b6c}.danger{color:#a52222;border-color:#efb3b3}.metrics{display:grid;grid-template-columns:repeat(6,1fr);gap:1px;padding:0;background:#dce3e8;border:1px solid #dce3e8;border-radius:8px;overflow:hidden}.metrics div{display:grid;gap:4px;padding:16px;background:#fff}.metrics span,small{font-size:.78rem;color:#607086}.metrics strong{font-size:1.35rem}nav{display:flex;gap:8px;margin:18px 0}section{background:#fff;border:1px solid #dce3e8;border-radius:8px;padding:16px;margin-top:16px}.toolbar{display:flex;align-items:center;gap:10px}.toolbar h2{margin-right:auto}input,select{min-height:40px;border:1px solid #cbd5df;border-radius:6px;padding:0 10px}.table{overflow:auto}table{width:100%;border-collapse:collapse;min-width:800px}th,td{text-align:left;padding:11px;border-top:1px solid #e8edf0}td small{display:block;margin-top:3px}.status{font-size:.75rem;font-weight:800;background:#eaf0f3;padding:4px 7px;border-radius:4px}.actions{display:flex;gap:5px}.settings{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.settings h2,.settings hr,.settings button{grid-column:1/-1}.settings label{display:grid;gap:5px;font-size:.85rem;font-weight:700}.settings label:first-of-type{display:flex;align-items:center}.settings hr{width:100%;border:0;border-top:1px solid #dce3e8}@media(max-width:850px){header{align-items:flex-start;flex-direction:column}.metrics{grid-template-columns:repeat(2,1fr)}nav{overflow:auto}.toolbar{align-items:stretch;flex-direction:column}.toolbar h2{margin:0}.settings{grid-template-columns:1fr}.settings h2,.settings hr,.settings button{grid-column:auto}}
  `]
})
export class AdminRewardsComponent implements OnInit {
  tab='redemptions'; metrics:any={}; redemptions:any[]=[]; referrals:any[]=[]; settings:any={}; query=''; status=''; statuses=['PENDING','PROCESSING','PAID','REJECTED','CLOSED']; adjustment={userId:'',amount:0,reason:''};
  constructor(private rewards:RewardsService,private toast:ToastService){}
  ngOnInit(){this.load();}
  get filteredRedemptions(){const q=this.query.toLowerCase();return this.redemptions.filter(x=>(!this.status||x.status===this.status)&&JSON.stringify(x).toLowerCase().includes(q));}
  get filteredReferrals(){const q=this.query.toLowerCase();return this.referrals.filter(x=>JSON.stringify(x).toLowerCase().includes(q));}
  load(){this.rewards.adminMetrics().subscribe(x=>this.metrics=x);this.rewards.adminRedemptions().subscribe(x=>this.redemptions=x);this.rewards.adminReferrals().subscribe(x=>this.referrals=x);this.rewards.adminSettings().subscribe(x=>this.settings=x);}
  transition(item:any,status:string,note?:string,paymentReference?:string){this.rewards.updateRedemption(item.requestId,status,note,paymentReference).subscribe({next:()=>{this.toast.show(`Redemption marked ${status.toLowerCase()}`,'success');this.load();},error:e=>this.toast.show(e.error?.error?.message||'Update failed','error')});}
  reject(item:any){const reason=prompt('Reason for rejection');if(reason?.trim())this.transition(item,'REJECTED',reason.trim());}
  markPaid(item:any){const reference=prompt('Bank payment reference');if(reference?.trim())this.transition(item,'PAID',undefined,reference.trim());}
  saveSettings(){this.rewards.updateSettings(this.settings).subscribe({next:x=>{this.settings=x;this.toast.show('Reward settings saved','success');},error:e=>this.toast.show(e.error?.error?.message||'Invalid settings','error')});}
  adjust(){if(!this.adjustment.userId||!this.adjustment.amount||!this.adjustment.reason.trim()){this.toast.show('User ID, non-zero amount, and reason are required','warning');return;}this.rewards.adjustWallet(this.adjustment.userId,this.adjustment.amount,this.adjustment.reason).subscribe({next:()=>{this.toast.show('Wallet adjusted','success');this.adjustment={userId:'',amount:0,reason:''};this.load();},error:e=>this.toast.show(e.error?.error?.message||'Adjustment failed','error')});}
  exportCsv(){this.rewards.exportRedemptions().subscribe(blob=>{const url=URL.createObjectURL(blob);const anchor=document.createElement('a');anchor.href=url;anchor.download='redemptions.csv';anchor.click();URL.revokeObjectURL(url);});}
}
